### PR TITLE
add accounts feature

### PR DESCRIPTION
**Pull request by gyorokpeter**

### CODE REVIEW

**Comment by Igoorx** [comment]
I think this needs some improvements before the merge

**Comment by gyorokpeter** [comment]
Can you be more specific? I'm aware that it's not complete, I just uploaded this to gather concrete feedback on which points could be prioritized/changed before merge.

**Comment by Igoorx** [comment]
it seems to be lacking some bot filtering and also proper name check in both client/server side, maybe this is not all but it is all that i could think for now

**Comment by Igoorx** [comment]
Is it missing something yet?

**Comment by gyorokpeter** [comment]
It should be functional from my perspective. Perhaps it would be a good idea to set up a dev instance with this code and test with a limited number of people.

**Pull request merged**
